version = 0.1
[default.deploy.parameters]
stack_name = "gold-notfiy"
resolve_s3 = true
s3_prefix = "gold-notfiy"
region = "ap-south-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
