AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Gold Price LK

  Sample SAM Template for Gold Price LK

Resources:
  # Lambda Function
  PriceCatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/gold_notify
        Handler: app.lambda_handler
        Runtime: python3.9
        Timeout: 900
        Architectures:
          - x86_64
        Events:
          ScheduleV2:
              Type: ScheduleV2
              Properties:
                  Name: 12HrsSchedule
                  ScheduleExpression: cron(0 12 * * ? *)
                  ScheduleExpressionTimezone: Asia/Colombo
                  State: ENABLED
        Environment:
          Variables:
            TELEBOT_KEY: '{{resolve:secretsmanager:general/prod:SecretString:TELEBOT_KEY:AWSCURRENT}}'